import Link from 'next/link';
import { ArrowLeft,CalendarClock,CheckCircle2,Database,Mail,MessageCircle,Phone,Search,ShieldCheck,UserRoundPlus,UsersRound,Globe2 } from 'lucide-react';
import { requireAdmin } from '@/lib/admin-auth';
import { CRM_LEAD_TYPES,CRM_PERMISSIONS,CRM_SOURCES,CRM_STATUSES,crmCategories,crmStats,listCrmLeads,syncCrmLifecycle } from '@/lib/crm';
import { addCrmLeadAction,syncBusinessResearchAction,updateCrmLeadAction } from './actions';

const labels:Record<string,string>={collected:'Gesammelt',contact_ready:'Kontakt bereit',contacted:'Kontaktiert',replied:'Geantwortet',qualified:'Qualifiziert',invited:'Eingeladen',converted:'Konvertiert',not_interested:'Kein Interesse',invalid:'Ungültig',do_not_contact:'Nicht kontaktieren',unknown:'Ungeklärt',allowed:'Erlaubt',consented:'Einwilligung',denied:'Nicht erlaubt',provider:'Handwerker / Partner',homeowner:'Eigentümer',public_intent:'Öffentliches Bedarfssignal',property:'Objektchance',other:'Sonstiger Lead',business_research:'SIN Business Research',business_research_intent:'Öffentliches Intent-Signal',business_research_property:'Offene Gebäudedaten',website:'Website',referral:'Empfehlung',facebook_group:'Facebook-Gruppe',forum:'Forum',community:'Community',campaign:'Kampagne',manual:'Manuell',existing_customer:'Bestandskunde'};
const compact=(n:number)=>new Intl.NumberFormat('de-DE',{notation:n>9999?'compact':'standard',maximumFractionDigits:1}).format(n);

export default async function CrmPage({searchParams}:{searchParams:Promise<Record<string,string|undefined>>}){
  await requireAdmin();
  const sp=await searchParams;
  const page=Number(sp.page||1)||1;
  syncCrmLifecycle();
  const stats=crmStats();
  const result=listCrmLeads({q:sp.q,status:sp.status,type:sp.type,category:sp.category,followup:sp.followup,page,limit:60});
  const categories=crmCategories();
  return <main className="min-h-screen bg-[#f3f6f4] px-4 py-6 text-[#1d2a22] md:px-8">
    <div className="mx-auto max-w-[1500px]">
      <header className="mb-6 flex flex-col gap-4 lg:flex-row lg:items-center lg:justify-between">
        <div><Link href="/admin" className="mb-3 inline-flex items-center gap-2 text-sm font-semibold text-[#105258]"><ArrowLeft size={16}/>Admin</Link><h1 className="text-3xl font-black tracking-[-.04em]">Leads & CRM</h1><p className="mt-1 text-sm text-[#68756c]">Handwerker, Eigentümer-Anfragen, öffentliche Bedarfssignale und Objektchancen in einer klaren Pipeline.</p></div>
        <form action={syncBusinessResearchAction}><button className="inline-flex items-center gap-2 rounded-xl bg-[#0e3d33] px-4 py-3 text-sm font-bold text-white shadow-sm"><Database size={17}/>Alle Research-Daten synchronisieren</button></form>
      </header>

      {(sp.sync||sp.created||sp.updated||sp.error)&&<div className={`mb-5 rounded-xl border px-4 py-3 text-sm ${sp.error?'border-red-200 bg-red-50 text-red-800':'border-green-200 bg-green-50 text-green-800'}`}>{sp.error?(sp.error==='contact-permission'?'Kontaktaktionen brauchen eine ausdrückliche Freigabe; „Nicht kontaktieren“ darf keinen Folgetermin haben.':'Aktion fehlgeschlagen. Bitte Quelle bzw. Eingaben prüfen.'):sp.sync?`${sp.sync} neue Datensätze importiert, ${sp.updated||0} aktualisiert, ${sp.deduplicated||0} zusammengeführt und ${sp.linked||0} Konten verknüpft.`:sp.updated?'Bestehender Lead zusammengeführt und aktualisiert.':'Lead gespeichert.'}</div>}

      <section className="mb-6 grid grid-cols-2 gap-3 md:grid-cols-3 xl:grid-cols-6">
        {[
          ['Gesamt',stats.total,UsersRound],['E-Mail',stats.email,Mail],['Telefon',stats.phone,Phone],['Fällig',stats.dueFollowUps,CalendarClock],['Social',stats.social,MessageCircle],['Antworten',(stats.byStatus.find(x=>x.status==='replied')?.count||0),CheckCircle2]
        ].map(([label,value,Icon]:any)=><article key={label} className="rounded-2xl border border-[#dfe6e0] bg-white p-4 shadow-[0_8px_28px_rgba(28,52,35,.04)]"><Icon size={18} className="mb-5 text-[#1b8569]"/><div className="text-2xl font-black">{compact(value)}</div><div className="mt-1 text-[11px] font-bold uppercase tracking-[.08em] text-[#7b887f]">{label}</div></article>)}
      </section>

      <section className="mb-5 rounded-2xl border border-[#dfe6e0] bg-white p-4 shadow-sm">
        <form method="get" className="grid gap-3 md:grid-cols-[minmax(240px,1fr)_170px_170px_200px_170px_auto]">
          <label className="relative"><Search size={16} className="absolute left-3 top-3.5 text-[#819087]"/><input name="q" defaultValue={sp.q||''} placeholder="Firma, Ort, PLZ, E-Mail, Telefon …" className="w-full rounded-xl border border-[#dce3dd] bg-[#fafcfa] py-3 pl-10 pr-3 text-sm outline-none focus:border-[#7fa8a2]"/></label>
          <select name="type" defaultValue={sp.type||''} className="rounded-xl border border-[#dce3dd] bg-white px-3 text-sm"><option value="">Alle Leadtypen</option>{CRM_LEAD_TYPES.map(x=><option key={x} value={x}>{labels[x]||x}</option>)}</select>
          <select name="status" defaultValue={sp.status||''} className="rounded-xl border border-[#dce3dd] bg-white px-3 text-sm"><option value="">Alle Status</option>{CRM_STATUSES.map(x=><option key={x} value={x}>{labels[x]||x}</option>)}</select>
          <select name="category" defaultValue={sp.category||''} className="rounded-xl border border-[#dce3dd] bg-white px-3 text-sm"><option value="">Alle Gewerke</option>{categories.map(x=><option key={x.category} value={x.category}>{x.category} · {compact(x.count)}</option>)}</select>
          <select name="followup" defaultValue={sp.followup||''} className="rounded-xl border border-[#dce3dd] bg-white px-3 text-sm"><option value="">Alle Folgetermine</option><option value="due">Heute / überfällig</option><option value="scheduled">Geplant</option><option value="none">Ohne Folgetermin</option></select>
          <button className="rounded-xl bg-[#e9f3e8] px-4 py-3 text-sm font-extrabold text-[#105258]">Filtern</button>
        </form>
      </section>

      <div className="grid gap-5 xl:grid-cols-[minmax(0,1fr)_360px]">
        <section className="overflow-hidden rounded-2xl border border-[#dfe6e0] bg-white shadow-sm">
          <div className="flex items-center justify-between border-b border-[#e7ece8] px-5 py-4"><div><strong className="text-sm">{result.total.toLocaleString('de-DE')} Leads</strong><p className="text-xs text-[#7a867e]">Seite {result.page} von {result.pages}</p></div><div className="flex gap-2">{result.page>1&&<Link className="rounded-lg border px-3 py-2 text-xs font-bold" href={{pathname:'/admin/crm',query:{...sp,page:String(result.page-1)}}}>Zurück</Link>}{result.page<result.pages&&<Link className="rounded-lg border px-3 py-2 text-xs font-bold" href={{pathname:'/admin/crm',query:{...sp,page:String(result.page+1)}}}>Weiter</Link>}</div></div>
          <div className="divide-y divide-[#edf0ed]">
            {result.rows.map(lead=>{const canContact=['allowed','consented'].includes(lead.contact_permission)&&lead.status!=='do_not_contact';return <article key={lead.id} className="grid gap-4 p-5 lg:grid-cols-[minmax(260px,1fr)_minmax(280px,1fr)]">
              <div className="min-w-0"><div className="mb-2 flex flex-wrap items-center gap-2"><span className={`rounded-full px-2.5 py-1 text-[10px] font-extrabold ${lead.lead_type==='provider'?'bg-[#e6f4e5] text-[#105258]':'bg-[#eef1ff] text-[#45569d]'}`}>{labels[lead.lead_type]||lead.lead_type}</span><span className="rounded-full bg-[#f1f3f1] px-2.5 py-1 text-[10px] font-bold text-[#606b63]">{labels[lead.status]||lead.status}</span></div><h2 className="truncate text-base font-black">{lead.company_name||lead.name}</h2>{lead.category&&<p className="mt-1 text-xs font-semibold text-[#647169]">{lead.category}</p>}<p className="mt-2 text-xs text-[#7b877f]">{[lead.address,lead.postcode,lead.locality].filter(Boolean).join(' · ')||'Ort nicht hinterlegt'}</p><div className="mt-3 flex flex-wrap gap-x-4 gap-y-2 text-xs">{lead.email&&(canContact?<a className="inline-flex items-center gap-1.5 font-semibold text-[#105258]" href={`mailto:${lead.email}`}><Mail size={13}/>{lead.email}</a>:<span className="inline-flex items-center gap-1.5 text-[#6f7b73]"><Mail size={13}/>{lead.email}</span>)}{lead.phone&&(canContact?<a className="inline-flex items-center gap-1.5 font-semibold text-[#105258]" href={`tel:${lead.phone}`}><Phone size={13}/>{lead.phone}</a>:<span className="inline-flex items-center gap-1.5 text-[#6f7b73]"><Phone size={13}/>{lead.phone}</span>)}{lead.website&&<a className="inline-flex items-center gap-1.5 font-semibold text-[#105258]" href={lead.website} target="_blank" rel="noreferrer"><Globe2 size={13}/>Website</a>}{lead.profile_url&&<a className="inline-flex items-center gap-1.5 font-semibold text-[#105258]" href={lead.profile_url} target="_blank" rel="noreferrer"><MessageCircle size={13}/>Social</a>}</div><p className="mt-3 text-[10px] text-[#8a948d]">Quelle: {labels[lead.source_type]||lead.source_type}{lead.source_detail?` · ${lead.source_detail}`:''}</p>{lead.next_follow_up_at&&<p className="mt-1 text-[10px] font-bold text-[#8a5b1f]">Folgekontakt: {new Date(`${lead.next_follow_up_at}T12:00:00`).toLocaleDateString('de-DE')}</p>}{lead.converted_user_id&&<p className="mt-1 text-[10px] font-bold text-[#105258]">Plattformkonto verknüpft</p>}</div>
              <form action={updateCrmLeadAction.bind(null,lead.id)} className="grid gap-2 rounded-xl bg-[#f8faf8] p-3 md:grid-cols-2"><label className="text-[10px] font-bold text-[#68756c]">Status<select name="status" defaultValue={lead.status} className="mt-1 w-full rounded-lg border bg-white p-2 text-xs">{CRM_STATUSES.map(x=><option key={x} value={x}>{labels[x]||x}</option>)}</select></label><label className="text-[10px] font-bold text-[#68756c]">Kontaktfreigabe<select name="permission" defaultValue={lead.contact_permission} className="mt-1 w-full rounded-lg border bg-white p-2 text-xs">{CRM_PERMISSIONS.map(x=><option key={x} value={x}>{labels[x]||x}</option>)}</select></label><label className="text-[10px] font-bold text-[#68756c]">Quelle<select name="sourceType" defaultValue={lead.source_type} className="mt-1 w-full rounded-lg border bg-white p-2 text-xs">{CRM_SOURCES.map(x=><option key={x} value={x}>{labels[x]||x}</option>)}</select></label><label className="text-[10px] font-bold text-[#68756c]">Quellendetail<input name="sourceDetail" defaultValue={lead.source_detail||''} className="mt-1 w-full rounded-lg border bg-white p-2 text-xs"/></label><label className="text-[10px] font-bold text-[#68756c]">Folgekontakt<input name="nextFollowUpAt" type="date" defaultValue={lead.next_follow_up_at||''} disabled={lead.status==='do_not_contact'||lead.contact_permission==='do_not_contact'} className="mt-1 w-full rounded-lg border bg-white p-2 text-xs disabled:opacity-50"/></label><label className="text-[10px] font-bold text-[#68756c]">Kanal<select name="channel" defaultValue="" className="mt-1 w-full rounded-lg border bg-white p-2 text-xs"><option value="">Keiner</option><option value="email">E-Mail</option><option value="phone">Telefon</option><option value="social">Social</option><option value="website">Website</option><option value="other">Sonstiges</option></select></label><label className="text-[10px] font-bold text-[#68756c]">Notiz<input name="notes" defaultValue={lead.notes||''} className="mt-1 w-full rounded-lg border bg-white p-2 text-xs" placeholder="z. B. Rückruf nächste Woche"/></label><button className="col-span-full rounded-lg bg-[#0e3d33] px-3 py-2 text-xs font-extrabold text-white">Speichern</button></form>
            </article>})}
            {result.rows.length===0&&<div className="p-12 text-center text-sm text-[#718077]">Keine Leads für diesen Filter.</div>}
          </div>
        </section>

        <aside className="space-y-5">
          <section className="rounded-2xl border border-[#dfe6e0] bg-white p-5 shadow-sm"><div className="mb-4 flex items-start gap-3"><div className="rounded-xl bg-[#e9f3e8] p-2 text-[#105258]"><UserRoundPlus size={18}/></div><div><h2 className="font-black">Lead hinzufügen</h2><p className="text-xs leading-5 text-[#718077]">Für Eigentümer z. B. Website-Anfrage, Empfehlung, Facebook-Gruppe, Forum oder Community dokumentieren.</p></div></div><form action={addCrmLeadAction} className="space-y-3">
            <div className="grid grid-cols-2 gap-2"><select name="leadType" defaultValue="provider" className="rounded-lg border p-2 text-xs">{CRM_LEAD_TYPES.map(x=><option key={x} value={x}>{labels[x]}</option>)}</select><select name="sourceType" defaultValue="manual" className="rounded-lg border p-2 text-xs">{CRM_SOURCES.map(x=><option key={x} value={x}>{labels[x]||x}</option>)}</select></div>
            <input name="name" required minLength={2} className="w-full rounded-lg border p-2.5 text-xs" placeholder="Name / Ansprechpartner"/><input name="companyName" className="w-full rounded-lg border p-2.5 text-xs" placeholder="Firma (optional)"/><input name="category" className="w-full rounded-lg border p-2.5 text-xs" placeholder="Gewerk / Interesse"/><div className="grid grid-cols-2 gap-2"><input name="postcode" className="rounded-lg border p-2.5 text-xs" placeholder="PLZ"/><input name="locality" className="rounded-lg border p-2.5 text-xs" placeholder="Ort"/></div><input type="hidden" name="country" value="DE"/><input name="email" type="email" className="w-full rounded-lg border p-2.5 text-xs" placeholder="E-Mail"/><input name="phone" className="w-full rounded-lg border p-2.5 text-xs" placeholder="Telefon"/><input name="website" className="w-full rounded-lg border p-2.5 text-xs" placeholder="Website"/><input name="profileUrl" className="w-full rounded-lg border p-2.5 text-xs" placeholder="Social-/Community-Profil URL"/><input name="sourceDetail" className="w-full rounded-lg border p-2.5 text-xs" placeholder="Quelle, Gruppe oder Kampagne"/><label className="block text-[10px] font-bold text-[#68756c]">Folgekontakt<input name="nextFollowUpAt" type="date" className="mt-1 w-full rounded-lg border p-2.5 text-xs"/></label><select name="permission" defaultValue="unknown" className="w-full rounded-lg border p-2.5 text-xs">{CRM_PERMISSIONS.map(x=><option key={x} value={x}>{labels[x]||x}</option>)}</select><textarea name="notes" rows={3} className="w-full rounded-lg border p-2.5 text-xs" placeholder="Interesse, Kontext, nächste Aktion …"/><button className="w-full rounded-xl bg-[#0e3d33] px-4 py-3 text-xs font-extrabold text-white">Lead speichern</button>
          </form></section>
          <section className="rounded-2xl border border-[#dbe5dc] bg-[#eff7ee] p-5"><div className="flex gap-3"><ShieldCheck size={20} className="shrink-0 text-[#105258]"/><div><strong className="text-sm">Kontaktstatus ist absichtlich getrennt</strong><p className="mt-1 text-xs leading-5 text-[#5c6b61]">Ein öffentlich gefundener Datensatz ist zunächst nur gesammelt. Das CRM verschickt keine automatische Kaltakquise. Einwilligung, erlaubter Kontaktweg und Widersprüche bleiben pro Lead nachvollziehbar.</p></div></div></section>
          <section className="rounded-2xl border border-[#dfe6e0] bg-white p-5"><h3 className="mb-3 text-sm font-black">Pipeline</h3><div className="space-y-2">{stats.byStatus.map(x=><div key={x.status} className="flex items-center justify-between text-xs"><span>{labels[x.status]||x.status}</span><strong>{x.count.toLocaleString('de-DE')}</strong></div>)}</div></section>
        </aside>
      </div>
    </div>
  </main>;
}
