const path = require('path');
const PptxGenJS = require('pptxgenjs');
const base = '/Users/jeremy/dev/einfach-hausen/presentation';
const cropDir = path.join(base, 'professional-crops');
const A = {
 webHero:path.join(cropDir,'01-website-startseite-hero.png'), webValue:path.join(cropDir,'01-website-startseite-value.png'), webProcess:path.join(cropDir,'03-website-so-funktionierts-process.png'), webLeistungenTop:path.join(cropDir,'02-website-leistungen-leistungen-top.png'), webLeistungenCards:path.join(cropDir,'02-website-leistungen-leistungen-cards.png'),
 ownerHomeTop:path.join(cropDir,'04-eigentuemer-app-start-viewport.png'), ownerHomeNext:path.join(cropDir,'04-eigentuemer-app-start-next.png'), ownerHausmeister:path.join(cropDir,'05-eigentuemer-app-hausmeister-viewport.png'), ownerHaus:path.join(cropDir,'06-eigentuemer-app-mein-haus-top.png'), ownerTarife:path.join(cropDir,'07-eigentuemer-app-tarife-top.png'), ownerTarife2:path.join(cropDir,'07-eigentuemer-app-tarife-prices.png'),
 partnerStart:path.join(cropDir,'08-handwerker-app-start-viewport.png'), partnerOrders:path.join(cropDir,'09-handwerker-app-auftraege-viewport.png'), partnerTeam:path.join(cropDir,'10-handwerker-app-team-top.png'), partnerTeam2:path.join(cropDir,'10-handwerker-app-team-members.png'), partnerProfilTop:path.join(cropDir,'11-handwerker-app-profil-top.png'), partnerProfilStatus:path.join(cropDir,'11-handwerker-app-profil-status.png')
};
const GREEN='0B6B43', LIGHT='F4F8F5', MINT='DDEEE6', DARK='141A17', MID='5E6B64', GOLD='D4A72C', WHITE='FFFFFF';
const pptx = new PptxGenJS(); pptx.layout='LAYOUT_WIDE'; pptx.author='Einfachhausen'; pptx.company='Einfachhausen'; pptx.subject='Live Produkt-Screenshots'; pptx.title='Einfachhausen Live Produktpräsentation'; pptx.lang='de-DE'; pptx.theme={headFontFace:'Aptos Display',bodyFontFace:'Aptos',lang:'de-DE'};
function bg(s,c=LIGHT){s.background={color:c};}
function title(s,t,sub){s.addText(t,{x:.55,y:.35,w:8.2,h:.45,fontFace:'Aptos Display',fontSize:25,bold:true,color:DARK,margin:0,fit:'shrink'}); if(sub)s.addText(sub,{x:.58,y:.83,w:8.0,h:.25,fontSize:8.7,color:MID,margin:0,fit:'shrink'});}
function footer(s,n){s.addText(`einfachhausen · Live-Screenshots · ${n}`,{x:.55,y:7.12,w:3.2,h:.16,fontSize:6.8,color:'7A867F',margin:0});}
function card(s,x,y,w,h,o={}){s.addShape(pptx.ShapeType.roundRect,{x,y,w,h,rectRadius:.12,fill:{color:o.fill||WHITE,transparency:o.transparency||0},line:{color:o.line||'D9E4DE',width:o.lw||.8},shadow:o.shadow===false?undefined:{type:'outer',color:'CAD6D0',opacity:.18,blur:1,angle:45,distance:1}});}
function label(s,text,x,y,w,color=GREEN){s.addText(text.toUpperCase(),{x,y,w,h:.18,fontSize:7.5,bold:true,color,margin:0,fit:'shrink'});}
function big(s,text,x,y,w,h,size=18){s.addText(text,{x,y,w,h,fontFace:'Aptos Display',fontSize:size,bold:true,color:DARK,margin:.03,fit:'shrink'});}
function body(s,text,x,y,w,h,size=10.5,color=MID){s.addText(text,{x,y,w,h,fontSize:size,color,margin:.03,fit:'shrink'});}
function bullet(s,items,x,y,w,h){s.addText(items.map(i=>({text:i,options:{bullet:{type:'bullet'}}})),{x,y,w,h,fontSize:10.3,color:DARK,margin:.04,fit:'shrink',paraSpaceAfterPt:5});}
function phone(s,file,x,y,w,h,cap){s.addShape(pptx.ShapeType.roundRect,{x:x-.035,y:y-.035,w:w+.07,h:h+.07,rectRadius:.18,fill:{color:'0E1411'},line:{color:'0E1411',width:.6},shadow:{type:'outer',color:'63756C',opacity:.25,blur:2,angle:45,distance:1.5}});s.addShape(pptx.ShapeType.roundRect,{x:x+.02,y:y+.03,w:w-.04,h:h-.06,rectRadius:.12,fill:{color:WHITE},line:{color:WHITE,width:.1}});s.addImage({path:file,x:x+.02,y:y+.03,w:w-.04,h:h-.06,sizing:{type:'crop',x:x+.02,y:y+.03,w:w-.04,h:h-.06}});s.addShape(pptx.ShapeType.roundRect,{x:x+w*.39,y:y+.02,w:w*.22,h:.045,rectRadius:.02,fill:{color:'0E1411'},line:{color:'0E1411',width:.1}});if(cap)s.addText(cap,{x,y:y+h+.1,w,h:.22,fontSize:8.2,bold:true,color:GREEN,align:'center',margin:0,fit:'shrink'});}
function desktop(s,file,x,y,w,h,cap){s.addShape(pptx.ShapeType.roundRect,{x:x-.04,y:y-.04,w:w+.08,h:h+.08,rectRadius:.08,fill:{color:WHITE},line:{color:'D6E2DB',width:.8},shadow:{type:'outer',color:'AAB8B0',opacity:.18,blur:2,angle:45,distance:1.2}});s.addImage({path:file,x,y,w,h,sizing:{type:'crop',x,y,w,h}});if(cap)s.addText(cap,{x,y:y+h+.12,w,h:.2,fontSize:8.2,bold:true,color:GREEN,align:'center',margin:0,fit:'shrink'});}
let s;
s=pptx.addSlide(); bg(s,'F7FAF8'); s.addShape(pptx.ShapeType.rect,{x:0,y:0,w:4.7,h:7.5,fill:{color:GREEN},line:{color:GREEN}}); s.addText('einfachhausen',{x:.62,y:.55,w:2.9,h:.34,fontSize:18,bold:true,color:WHITE,margin:0}); s.addText('Live Produktpräsentation',{x:.62,y:2.12,w:3.4,h:.88,fontFace:'Aptos Display',fontSize:30,bold:true,color:WHITE,margin:0,fit:'shrink'}); s.addText('Website · Eigentümer-App · Handwerker-App',{x:.65,y:3.2,w:3.6,h:.28,fontSize:11,color:'DDEEE6',margin:0}); s.addText('Aktueller Produktionsstand, kuratiert für Team-Review und nächste Entscheidungen.',{x:.65,y:3.68,w:3.55,h:.55,fontSize:10.5,color:'EAF5EF',margin:0,fit:'shrink'}); s.addText('Live verifiziert: GitHub main = Produktion · Healthcheck ok · Datenbank ready',{x:.65,y:6.62,w:3.55,h:.26,fontSize:7.8,color:'CBE6D8',margin:0,fit:'shrink'}); desktop(s,A.webHero,5.15,.68,4.75,2.75,'Website Einstieg'); phone(s,A.ownerHomeTop,9.15,2.75,1.85,3.98,'Eigentümer'); phone(s,A.partnerStart,10.75,2.05,1.85,3.98,'Handwerker');
s=pptx.addSlide(); bg(s); title(s,'Drei Oberflächen, ein operativer Ablauf','Vom ersten Interesse bis zur geprüften Ausführung.'); ['Website','Eigentümer-App','Handwerker-App'].forEach((name,i)=>{const xs=[.8,4.65,8.5][i], roles=['Vertrauen aufbauen, Angebot erklären und Leads aktivieren.','Anliegen, Hausakte, Tarife und Freigabe sauber bündeln.','Partner prüfen, Aufträge strukturieren und Teamfähigkeit vorbereiten.'][i], imgs=[A.webHero,A.ownerHomeTop,A.partnerStart][i]; card(s,xs,1.35,3.35,4.8,{fill:WHITE}); label(s,name,xs+.25,1.65,2.8); big(s,roles,xs+.25,1.98,2.85,.75,15); if(i===0)desktop(s,imgs,xs+.3,3.05,2.75,1.75); else phone(s,imgs,xs+.9,3.03,1.28,2.7);}); footer(s,2);
s=pptx.addSlide(); bg(s); title(s,'Website: Klarer Einstieg, starke Marke','Die Startseite muss sofort Vertrauen, Nutzen und Handlung auslösen.'); desktop(s,A.webHero,.7,1.25,7.2,4.35,'Live-Crop: Above the fold'); label(s,'CEO-Lesart',8.25,1.3,2.3); big(s,'Der erste Screen verkauft das Versprechen: einfach, betreut, lokal.',8.25,1.65,3.9,.95,20); bullet(s,['Logo und Claim wirken ruhig und seriös.','Hero-Bereich erklärt den Nutzen ohne Techniküberladung.','CTA muss prominent bleiben: Besucher direkt in Anfrage oder Beratung führen.'],8.25,2.95,3.8,1.35); card(s,8.25,5.05,3.7,.82,{fill:MINT,line:'C7DED1'}); big(s,'Team-Check',8.48,5.23,1.5,.22,12); body(s,'Ist der primäre CTA auf jedem Breakpoint dominant genug?',9.55,5.18,2.1,.32,8.6,DARK); footer(s,3);
s=pptx.addSlide(); bg(s); title(s,'Website: Leistungen und Ablauf greifbar machen','Nicht alles zeigen – die besten Beweisstellen herausgreifen.'); desktop(s,A.webLeistungenTop,.65,1.1,5.65,2.65,'Leistungen'); desktop(s,A.webProcess,6.85,1.1,5.65,2.65,'So funktioniert’s'); desktop(s,A.webLeistungenCards,1.1,4.45,4.6,1.55,'Karten / Nutzenmodule'); desktop(s,A.webValue,7.3,4.45,4.6,1.55,'Vertrauen / Value'); footer(s,4);
s=pptx.addSlide(); bg(s); title(s,'Eigentümer-App: Startscreen als Kommandozentrale','Ein Eigentümer soll sofort wissen: Was ist wichtig, was kann ich tun?'); phone(s,A.ownerHomeTop,.95,1.05,2.05,4.45,'Home'); card(s,3.55,1.28,4,1.15); label(s,'Wichtig',3.8,1.48,1.8); big(s,'Hausmeister zuerst',3.8,1.75,3.3,.3,18); body(s,'Das Anliegen wird niedrigschwellig formuliert: schreiben, sprechen oder Foto zeigen.',3.8,2.08,3.3,.3,9.5); card(s,3.55,3,4,1.15); label(s,'Sicherheit',3.8,3.2,1.8); big(s,'Keine Freigabe ohne Nutzer',3.8,3.47,3.3,.3,18); body(s,'Kein Auftrag startet ohne ausdrückliche Auswahl.',3.8,3.8,3.3,.3,9.5); desktop(s,A.ownerHomeNext,8.25,1.55,3.65,4,'Weiter unten: nächste Schritte'); footer(s,5);
s=pptx.addSlide(); bg(s); title(s,'Eigentümer-App: Anliegenaufnahme ohne Reibung','Der Hausmeister-Flow ist der zentrale Produktmoment.'); phone(s,A.ownerHausmeister,.85,.98,2.18,4.75,'Hausmeister'); s.addShape(pptx.ShapeType.chevron,{x:3.55,y:2.8,w:.55,h:.45,fill:{color:GREEN},line:{color:GREEN}}); card(s,4.55,1.25,3.35,3.6); label(s,'Flow',4.85,1.55,1.5); big(s,'Text, Foto oder Sprache',4.85,1.9,2.75,.55,19); body(s,'Der Nutzer beschreibt nur, was los ist. Einfachhausen klärt zuerst und erstellt nur bei Freigabe einen Auftrag.',4.85,2.65,2.65,.82,10); card(s,8.6,1.25,3.7,3.6,{fill:'FEFAF0',line:'E7D6A7'}); label(s,'Produktversprechen',8.9,1.55,2.2,GOLD); big(s,'Weniger Hotline, mehr Struktur',8.9,1.9,2.9,.55,19); bullet(s,['Anliegen landet standardisiert.','Mediennachweise werden direkt möglich.','Menschlicher Ansprechpartner bleibt erreichbar.'],8.9,2.65,2.85,1.1); footer(s,6);
s=pptx.addSlide(); bg(s); title(s,'Eigentümer-App: Hausakte und Tarife als Bindung','Der Nutzer sieht nicht nur Support, sondern dauerhaftes Zuhause-Management.'); phone(s,A.ownerHaus,.85,1,1.75,3.8,'Hausakte'); phone(s,A.ownerTarife,2.25,1,1.75,3.8,'Tarife'); phone(s,A.ownerTarife2,3.65,1,1.75,3.8,'Preise'); card(s,6.1,1.25,5.25,1.2); label(s,'Hausakte',6.4,1.45,1.8); big(s,'Der Datenanker für Technik, Wartung, Dokumente und Historie.',6.4,1.73,4.55,.35,17); card(s,6.1,3,5.25,1.2); label(s,'Tarife',6.4,3.2,1.8); big(s,'Monetarisierung wird sichtbar – ohne den Support-Flow zu stören.',6.4,3.48,4.55,.35,17); body(s,'Empfehlung: Im Team prüfen, ob Tarifnamen und Leistungsgrenzen im Live-Screen schon verkaufsstark genug sind.',6.4,5.05,4.7,.45,10,DARK); footer(s,7);
s=pptx.addSlide(); bg(s); title(s,'Handwerker-App: Vertrauen durch kontrollierten Zugang','Der Live-Zustand zeigt bewusst: Erst prüfen, dann Aufträge freischalten.'); phone(s,A.partnerStart,.95,1,2.05,4.45,'Partnerzugang'); card(s,3.8,1.35,3.6,2.4,{fill:'FEFAF0',line:'E7D6A7'}); label(s,'Aktueller Live-Status',4.1,1.6,2.2,GOLD); big(s,'Unternehmensprüfung ausstehend',4.1,1.95,2.85,.75,19); body(s,'Das ist kein Fehler, sondern ein wichtiger Sicherheits- und Qualitätsmechanismus.',4.1,2.85,2.9,.42,9.5,DARK); card(s,8,1.35,3.65,2.4); label(s,'CEO-Entscheidung',8.3,1.6,2); big(s,'Partnerfähigkeit vor Volumen',8.3,1.95,2.85,.55,19); bullet(s,['Status eindeutig sichtbar.','CTA führt zum Partnerstatus.','Kein Auftrag ohne Prüfung.'],8.3,2.68,2.8,.9); footer(s,8);
s=pptx.addSlide(); bg(s); title(s,'Handwerker-App: Aufträge und Teamstruktur vorbereitet','Die App bildet den späteren operativen Alltag ab.'); phone(s,A.partnerOrders,.95,1,2.05,4.45,'Aufträge'); phone(s,A.partnerTeam,3,1,2.05,4.45,'Team'); phone(s,A.partnerTeam2,5.05,1,2.05,4.45,'Teamdetails'); card(s,8.05,1.35,3.85,1.2); label(s,'Aufträge',8.35,1.55,1.8); big(s,'Noch leer – aber eindeutig vorbereitet.',8.35,1.83,3.1,.32,17); card(s,8.05,3.05,3.85,1.2); label(s,'Team',8.35,3.25,1.8); big(s,'Rollen und Teamverwaltung skalieren Partnerbetrieb.',8.35,3.53,3.1,.32,17); body(s,'Leerer Zustand nicht verstecken, sondern als kontrollierten Rollout erklären.',8.35,5,3.1,.45,10,DARK); footer(s,9);
s=pptx.addSlide(); bg(s); title(s,'Handwerker-App: Profil als Prüf- und Qualitätszentrale','Nicht ein langes Formular zeigen, sondern die relevanten Statusbereiche.'); phone(s,A.partnerProfilTop,.95,.95,2.05,4.45,'Profil oben'); phone(s,A.partnerProfilStatus,3.15,.95,2.05,4.45,'Statusbereich'); card(s,6.05,1.2,5.25,1.1); label(s,'Wofür das wichtig ist',6.35,1.4,2.3); big(s,'Der Partnerstatus wird zum operativen Gate.',6.35,1.68,4.55,.28,17); bullet(s,['Unternehmensdaten und Vertragsstatus bündeln.','Qualifikation ist sichtbar, bevor Nachfrage verteilt wird.','Rollout kann kontrolliert pro Partner erfolgen.'],6.35,2.65,4.45,1.15); card(s,6.05,4.55,5.25,.9,{fill:MINT,line:'C7DED1'}); body(s,'Präsentationshinweis: Beim Demo-Konto ist die Prüfung ausstehend. Für Sales-Demos zusätzlich ein freigeschaltetes Partnerkonto aufnehmen.',6.35,4.72,4.65,.34,9.2,DARK); footer(s,10);
s=pptx.addSlide(); bg(s); title(s,'Professionelle Bewertung: Was wirkt stark, was fehlt noch?','Aus den Live-Screenshots abgeleitete CEO-Punkte.'); ['Stark','Schärfen','Nächster Schritt'].forEach((h,i)=>{const x=[.85,4.75,8.65][i], texts=[['Ruhige Marke, klare Navigation.','Hausmeister-Flow ist sofort verständlich.','Partnergate schützt Qualität.'],['Website-CTA konsistenter priorisieren.','Tarife verkaufsstärker formulieren.','Demo-Daten für Präsentation vorbereiten.'],['Freigeschaltetes Partnerkonto anlegen.','3–5 echte Beispiel-Anliegen ins CRM bringen.','Präsentationsmodus mit anonymisierten Daten bauen.']][i]; card(s,x,1.35,3.25,4.55,{fill:i===0?MINT:WHITE,line:i===1?'D9E4DE':'C7DED1'}); label(s,h,x+.25,1.65,2.4,i===2?GOLD:GREEN); bullet(s,texts,x+.35,2.25,2.65,2.2);}); footer(s,11);
s=pptx.addSlide(); bg(s,GREEN); s.addText('Live-Nachweis',{x:.75,y:.68,w:3.4,h:.5,fontFace:'Aptos Display',fontSize:28,bold:true,color:WHITE,margin:0}); s.addText('Diese Version wurde aus den aktuellen Produktions-Screenshots unter presentation/ neu aufgebaut und kuratiert.',{x:.78,y:1.38,w:5.3,h:.35,fontSize:11,color:'EAF5EF',margin:0}); [['Quelle','https://einfachhausen.de'],['GitHub / Produktion','main = 3a8aa93'],['Healthcheck','ok=true · database=ready'],['Assets','11 Screenshots · Crops statt Lang-Screenshots']].forEach((f,i)=>{card(s,.85,2.15+i*.85,5.5,.55,{fill:WHITE,line:'BFD8CB',shadow:false}); s.addText(f[0],{x:1.1,y:2.31+i*.85,w:1.5,h:.12,fontSize:8,bold:true,color:GREEN,margin:0}); s.addText(f[1],{x:2.65,y:2.28+i*.85,w:3.25,h:.18,fontSize:10.5,color:DARK,margin:0,fit:'shrink'});}); desktop(s,A.webHero,7,.95,4.8,2.8); phone(s,A.ownerHomeTop,7.55,4.15,1.15,2.5); phone(s,A.partnerStart,8.8,4.15,1.15,2.5); phone(s,A.partnerOrders,10.05,4.15,1.15,2.5);
pptx.writeFile({fileName:path.join(base,'einfachhausen-live-professional-2026-08-26.pptx')});
