import type {ReactNode} from "react";
import {EHLogo, EHButton} from "./primitives";
import s from "./styles.module.css";
export function EHWorkspaceFrame({navigation,account,mobileMenu,notifications,context,children,homeHref,bottomNav}: {navigation:ReactNode;account:ReactNode;mobileMenu:ReactNode;notifications:ReactNode;context:string;children:ReactNode;homeHref:string;bottomNav:ReactNode}) {
 return <div className={s.workspace}><aside className={s.workspaceSidebar}><EHLogo href={homeHref}/><nav aria-label="Hauptnavigation" className={s.workspaceNav}>{navigation}</nav><div className={s.workspaceAccount}>{account}</div></aside><main className={s.workspaceMain}><header className={s.workspaceTop}><div className={s.workspaceMobile}>{mobileMenu}<EHLogo href={homeHref}/></div><span className={s.workspaceContext}>{context}</span><div className={s.workspaceTools}>{notifications}</div></header><div className={s.workspaceContent}>{children}</div></main><div className={s.workspaceBottom}>{bottomNav}</div></div>;
}
export function EHWorkspaceNavItem({href,active,icon,children}:{href:string;active:boolean;icon:ReactNode;children:ReactNode}) {return <a href={href} aria-current={active?"page":undefined}>{icon}<span>{children}</span></a>;}
export function EHWorkspaceGrid({main,aside}:{main:ReactNode;aside:ReactNode}) {return <div className={s.workspaceGrid}><div className={s.workspaceColumn}>{main}</div><aside className={s.workspaceColumn}>{aside}</aside></div>;}
export function EHWorkSection({title,children,link}:{title:string;children:ReactNode;link?:{href:string;label:string}}) {return <section className={s.workSection}><header><h2>{title}</h2>{link&&<a href={link.href}>{link.label} →</a>}</header>{children}</section>;}
export function EHPriorityAction({eyebrow,title,text,href,label}:{eyebrow:string;title:string;text:string;href:string;label:string}) {return <section className={s.priorityAction}><div><p>{eyebrow}</p><h2>{title}</h2><p>{text}</p></div><EHButton href={href} variant="on-dark" arrow>{label}</EHButton></section>;}
export function EHWorkMetrics({items}:{items:{label:string;value:number|string;href:string;hint?:string}[]}) {return <nav className={s.workMetrics} aria-label="Arbeitsübersicht">{items.map(item=><a key={item.href} href={item.href}><strong>{item.value}</strong><span>{item.label}</span>{item.hint&&<small>{item.hint}</small>}</a>)}</nav>;}
export function EHServiceDirectory({groups}:{groups:{title:string;items:{href:string;title:string;text:string;icon:ReactNode}[]}[]}) {return <div className={s.serviceDirectory}>{groups.map(group=><section key={group.title}><h2>{group.title}</h2><div>{group.items.map(item=><a key={item.href} href={item.href}><span className={s.directoryIcon}>{item.icon}</span><span><strong>{item.title}</strong><span>{item.text}</span></span><span aria-hidden="true">↗</span></a>)}</div></section>)}</div>;}
export function EHRequestList({items}:{items:{id:string;kind:string;title:string;description:string;location:string;price?:string|null;time:string;href:string}[]}) {return <div className={s.requestList}>{items.map(item=><a key={item.id} href={item.href}><div><span className={s.requestKind}>{item.kind}</span><h3>{item.title}</h3><p>{item.description}</p><small>{item.location} · {item.time}</small></div><div className={s.requestAction}>{item.price&&<strong>{item.price}</strong>}<span>Vorgang öffnen ↗</span></div></a>)}</div>;}
