"use client";
import {useState} from "react";
import {EHScope,EHSection,EHLogo,EHHeading,EHText,EHTextLink,EHButton,EHActions,EHTabs,EHField,EHInput,EHTextarea,EHSelect,EHCheckbox,EHDialog,EHStatus,EHLoadingState,EHErrorState,EHEmptyState,EHFAQ,EHComparison,EHFacts,EHCallout,EHPanel} from "@/design-system";
import {EHHomePage,EHServicePage,EHArticlePage,EHServiceIndexPage,EHContactPage,EHPricingPage,EHOwnerPage,EHProviderPage} from "../../../packages/eh-design/src/recipes";
import {EHJobDetailPage,EHAppointmentsPage,EHMessageThreadPage,EHBillingPage,EHSettingsPage,EHAccessPage,EHGlossaryEntryPage,EHSensitiveServicePage} from "../../../packages/eh-design/src/domain-recipes";
const image={src:"/images/marketing/family-home.jpg",alt:"Ein Paar vor einem Haus im Garten",caption:"Illustrative Bildwelt – kein Kundenbeispiel."};
const faq=[{q:"Wird durch meine Anfrage bereits etwas beauftragt?",a:"Nein. Eine Beauftragung erfolgt erst nach deiner ausdrücklichen Entscheidung."},{q:"Kann ich bestehende Unterlagen weiter nutzen?",a:"Deine Dokumente bleiben die Grundlage. Die Hausakte hilft, sie gemeinsam zu ordnen."}];
const services=[{title:"Heizung & Wärme",href:"#service",text:"Wartung, Reparatur und die richtigen Fragen für dein Zuhause."},{title:"Dach & Fassade",href:"#service",text:"Die Gebäudehülle im Blick behalten."},{title:"Garten & Außenbereich",href:"#service",text:"Anstehende Arbeiten verständlich einordnen."}];
export function DesignShowcase() {
  const [view,setView]=useState("home");const [receipt,setReceipt]=useState("");const [dialog,setDialog]=useState(false);
  const views=[["home","Startseite"],["service","Leistung"],["article","Ratgeber"],["index","Leistungsübersicht"],["contact","Kontakt"],["pricing","Leistungsumfang"],["owner","Owner-App"],["provider","Handwerker-App"],["job","Auftrag"],["terms","Termine"],["thread","Gespräch"],["billing","Rechnungen"],["settings","Einstellungen"],["access","Anmeldung"],["glossary","Lexikon"],["sensitive","Notfall"],["components","Bausteine"]];
  const go=(id:string)=>{setView(id);window.scrollTo({top:0});};
  const form=<form onSubmit={e=>{e.preventDefault();setReceipt("Vorschau: Formular geprüft. Es wurde nichts versendet.");}}><EHField id="contact-name" label="Dein Name" required><EHInput id="contact-name" name="name" autoComplete="name" required/></EHField><EHField id="contact-email" label="Deine E-Mail-Adresse" required><EHInput id="contact-email" name="email" type="email" autoComplete="email" required/></EHField><EHField id="contact-message" label="Dein Anliegen" required><EHTextarea id="contact-message" name="message" required/></EHField><EHCheckbox label="Ich habe den Vorschauhinweis gelesen." required/><EHButton type="submit" arrow>Formular prüfen</EHButton>{receipt && <EHText>{receipt}</EHText>}</form>;
  return <EHScope><EHSection compact><EHActions><EHLogo/><div><EHHeading as="h2" scale="item">Die Einfachhausen Bibliothek.</EHHeading><EHText size="meta">Verbindlicher Stil · Atelier 02 · Version 1.0 · Inhalte dieser Ansicht sind gekennzeichnete Beispiele.</EHText></div></EHActions><EHActions>{views.map(([id,label])=><EHButton key={id} variant={view===id ? "primary":"secondary"} size="small" onClick={()=>go(id)}>{label}</EHButton>)}</EHActions></EHSection><main id="design-preview">
  {view==="home" && <EHHomePage image={image} accountHref="/hausakte" contactHref="/kontakt"/>}
  {view==="service" && <EHServicePage title="Damit Wärme einfach bleibt." description="Wenn die Heizung Fragen aufwirft, hilft ein klarer Überblick: Was ist bekannt, was steht an und wer kann weiterhelfen?" image={image} benefits={[{title:"Verständlich.",text:"Dein Anliegen in deinen Worten."},{title:"Nachvollziehbar.",text:"Unterlagen und Vereinbarungen zusammenhalten."},{title:"Mit Entscheidung.",text:"Du bestimmst, was beauftragt wird."}]} scope={[{title:"Wartung vorbereiten",text:"Vorhandene Unterlagen und den aktuellen Zustand zusammenstellen."},{title:"Fragen klären",text:"Bedarf und Zuständigkeit mit einem passenden Ansprechpartner besprechen."},{title:"Wissen bewahren",text:"Erledigte Arbeiten in der Hausakte dokumentieren."}]} steps={[{title:"Anliegen beschreiben",text:"Was fällt dir auf? Was möchtest du klären?"},{title:"Nächsten Schritt abstimmen",text:"Umfang und Ansprechpartner gemeinsam einordnen."},{title:"Selbst entscheiden",text:"Vereinbarungen prüfen, bevor etwas beauftragt wird."}]} faq={faq} contactHref="/kontakt"/>}
  {view==="article" && <EHArticlePage category="Hauswissen · Musterartikel" title="Ein guter Überblick beginnt mit drei Unterlagen." description="Wie du die Geschichte deines Hauses Stück für Stück zusammenbringst." readingTime="3 Minuten Lesezeit" contents={[{id:"documents",title:"Vorhandenes sammeln"},{id:"order",title:"Zusammenhänge erhalten"},{id:"next",title:"Den nächsten Schritt festhalten"}]} related={services}><h2 id="documents">Vorhandenes sammeln.</h2><p>Beginne mit dem, was du schon hast: Rechnungen, Bedienungsanleitungen und Dokumentation zu ausgeführten Arbeiten. Vollständigkeit entsteht mit der Zeit.</p><h2 id="order">Zusammenhänge erhalten.</h2><p>Ein Datum, der betroffene Bereich und die beteiligten Menschen machen aus einzelnen Dateien eine nachvollziehbare Geschichte.</p><EHCallout title="Ein hilfreicher Anfang">Ordne eine Rechnung direkt der Arbeit zu, für die sie ausgestellt wurde. So bleibt der Zusammenhang später verständlich.</EHCallout><h2 id="next">Den nächsten Schritt festhalten.</h2><p>Notiere offene Fragen und anstehende Termine. Du musst nicht jede Antwort sofort kennen, um einen guten Überblick zu gewinnen.</p></EHArticlePage>}
  {view==="index" && <EHServiceIndexPage title="Was steht bei deinem Haus an?" text="Jedes Haus hat seine Themen. Hier beginnt der passende nächste Schritt." items={services} contactHref="/kontakt"/>}
  {view==="contact" && <EHContactPage text="Beschreibe, was dich beschäftigt. Gemeinsam wird der nächste Schritt klar." image={{src:"/images/marketing/partner-doorstep.jpg",alt:"Zwei Menschen im Gespräch an einer Haustür",caption:"Illustrative Bildwelt – keine Mitarbeitervorstellung."}} form={form} contactDetails={<EHText size="meta">Dies ist eine Formularvorschau. Es wird keine Nachricht versendet.</EHText>}/>}
  {view==="pricing" && <EHPricingPage title="Der passende Umfang für dein Haus." text="Gestaltungsbeispiel für Leistungsmodelle. Diese Ansicht veröffentlicht keine Tarife." plans={[{name:"Hausakte",price:"Nach aktuellem Angebot",text:"Der Ort für Unterlagen und die Geschichte deines Hauses.",features:["Dokumente zusammenhalten","Wichtige Informationen wiederfinden"],href:"/kontakt",action:"Umfang erfragen"},{name:"Persönliche Begleitung",price:"Individuell vereinbart",text:"Wenn du Unterstützung beim nächsten Schritt brauchst.",features:["Anliegen gemeinsam einordnen","Leistungsumfang vorab besprechen"],href:"/kontakt",action:"Bedarf besprechen"}]} note="Beispiel für die Komponente. Verbindliche Preise müssen aus dem freigegebenen Produktangebot stammen." faq={faq}/>}
  {view==="owner" && <EHOwnerPage houseName="Mein Haus" address="Musterhaus · unverbindliche Vorschau" documents={[{id:"d1",title:"Heizungswartung · Musterdatei",category:"Heizung",date:"Juli 2026",href:"#documents"},{id:"d2",title:"Dachinspektion · Musterdatei",category:"Dach",date:"Mai 2026",href:"#documents"}]} history={[{when:"Juli 2026",title:"Wartung dokumentiert",text:"Beispieleintrag in der Hauschronik."},{when:"Als Nächstes",title:"Unterlagen ergänzen",current:true}]} people={[{id:"p1",title:"Ansprechpartner ergänzen",text:"Hier stehen später deine tatsächlichen Kontakte."}]} onRequest={()=>{setReceipt("Vorschau: Dein Anliegen wurde nicht versendet.");setDialog(true);}}/>}
  {view==="provider" && <EHProviderPage name="Dein Überblick." summary="Beispieldaten für Anfragen, Aufträge und Termine." requests={[{id:"r1",title:"Heizungswartung abstimmen",location:"Musteranfrage · kein echter Auftrag",status:"Rückfrage offen"},{id:"r2",title:"Dachrinne prüfen",location:"Musteranfrage · kein echter Auftrag",status:"Neu"}]} appointments={[{id:"a1",time:"09:00 Uhr",title:"Mustertermin",address:"Beispieladresse"}]} onOpenRequest={()=>{setReceipt("Beispielanfrage. Hier wird die bestehende Auftragsansicht angebunden.");setDialog(true);}}/>}
  {view==="components" && <EHSection><EHHeading>Für die echten Details.</EHHeading><EHText>Formulare, Zustände, Register, Vergleich und Dialog – mit derselben visuellen Grundlage.</EHText><EHTabs label="Komponentenfamilien" tabs={[{id:"forms",label:"Formulare",content:<EHPanel title="Eingaben">{form}<EHField id="topic" label="Thema"><EHSelect id="topic"><option>Heizung</option><option>Dach</option></EHSelect></EHField></EHPanel>},{id:"states",label:"Zustände",content:<><EHActions><EHStatus>Offen</EHStatus><EHStatus tone="success">Erledigt</EHStatus><EHStatus tone="warning">Rückfrage</EHStatus><EHStatus tone="error">Fehler</EHStatus></EHActions><EHLoadingState/><EHErrorState text="Beispiel für einen fehlgeschlagenen Abruf." onRetry={()=>setReceipt("Erneut geprüft.")}/><EHEmptyState title="Noch keine Unterlagen" text="Deine Dokumente finden hier ihren Platz." action={<EHButton onClick={()=>setDialog(true)}>Dialog öffnen</EHButton>}/></>},{id:"content",label:"Inhalte",content:<><EHComparison left={{title:"Einzelne Unterlagen",items:["Verteilt abgelegt","Zusammenhänge suchen"]}} right={{title:"Eine Hausgeschichte",items:["Gemeinsam auffindbar","Vorgänge nachvollziehen"]}}/><EHFacts items={[{value:"01",label:"Unterlagen"},{value:"02",label:"Termine"},{value:"03",label:"Menschen"}]}/><EHFAQ items={faq}/></>}]} /></EHSection>}
  
  {view==="job" && <EHJobDetailPage title="Heizung macht Geräusche (BEISPIEL)" reference="Vorgang EH-0001 · Beispiel" summary="Beispieldaten zur Ansicht. Es wird nichts beauftragt." status={{label:"In Klärung",tone:"info"}} facts={[{label:"Bereich",value:"Heizung & Wärme"},{label:"Erstellt",value:"01.09.2026"}]} nextStep={{title:"Nächster Schritt",text:"Anliegen prüfen, dann Umfang abstimmen.",action:{label:"Details ansehen",href:"#job"}}} history={[{when:"01.09.2026",title:"Anliegen beschrieben",text:"Beispiel"}]} documents={[{id:"d1",title:"Foto Heizung (Beispiel)",category:"Foto",date:"01.09.2026",href:"#job"}]} contacts={[{id:"c1",title:"Max Musterpartner (Beispiel)",text:"Heizung & Sanitär"}]}/>}
  {view==="terms" && <EHAppointmentsPage period="September 2026 (BEISPIEL)" groups={[{id:"g1",dateLabel:"Montag, 08.09.2026",appointments:[{id:"a1",time:"10:00",title:"Wartung Heizung (BEISPIEL)",location:"Zuhause",href:"#terms",status:{label:"Bestätigt",tone:"success"}}]}]} navigation={{previous:{label:"Zurück",href:"#terms"},today:{label:"Heute",href:"#terms"},next:{label:"Weiter",href:"#terms"}}}/>}
  {view==="thread" && <EHMessageThreadPage title="Heizungswartung (BEISPIEL)" context="Vorgang EH-0001 · Beispieldaten" back={{label:"Zurück zur Übersicht",href:"#thread"}} messages={[{id:"m1",author:"Eigentümer (BEISPIEL)",sentAt:"01.09.2026 10:00",body:"Die Heizung macht seit gestern Geräusche.",delivery:{label:"Gesendet",tone:"info"}},{id:"m2",author:"Partnerbetrieb (BEISPIEL)",sentAt:"01.09.2026 11:30",body:"Danke, wir schauen uns das an.",delivery:{label:"Gelesen",tone:"success"}}]} reply={{onSubmit: async ()=>{setReceipt("Vorschau: Nachricht geprüft. Es wurde nichts versendet.");}}}/>}
  {view==="billing" && <EHBillingPage text="Beispieldaten zur Ansicht." note="Rechnungen bleiben mit Vorgang und Dokument verknüpft." rows={[{id:"r1",number:"RE-2026-001",party:"Musterbetrieb (BEISPIEL)",date:"02.09.2026",amount:"149,00 €",status:{label:"Offen",tone:"warning"},document:{label:"Beleg ansehen",href:"#billing"}}]} action={{label:"Alle Belege",href:"#billing"}}/>}
  {view==="settings" && <EHSettingsPage text="Beispieldaten zur Ansicht. Es wird nichts gespeichert." groups={[{id:"g1",title:"Benachrichtigungen (BEISPIEL)",description:"Welche Hinweise möchtest du erhalten?",fields:<EHCheckbox label="Wartungserinnerung (BEISPIEL)"/>}]} onSubmit={e=>{e.preventDefault();setReceipt("Vorschau: Einstellungen geprüft. Es wurde nichts gespeichert.");}} pending={false} securityAction={{title:"Konto schließen (BEISPIEL)",text:"Getrennte sensible Aktion.",button:{children:"Schließen anfragen",variant:"secondary"}}}/>}
  {view==="access" && <EHAccessPage title="Anmelden (BEISPIEL)" text="Beispielansicht. Es erfolgt keine Anmeldung." eyebrow="Zugang" form={form} help={[{label:"Hilfe",href:"#access"}]} legal={<EHText size="meta">Mit der Nutzung gelten die <EHTextLink href="#access">AGB (BEISPIEL)</EHTextLink>.</EHText>}/>}
  {view==="glossary" && <EHGlossaryEntryPage term="Wartungsintervall (BEISPIEL)" category="Hauswissen" definition="Beispieldefinition: Abstand zwischen zwei Wartungen einer Anlage." sections={[{id:"s1",title:"Worum geht es",paragraphs:["Beispielabsatz zur Ansicht."]}]} related={[{title:"Heizungswartung (BEISPIEL)",href:"#glossary",text:"Verwandter Begriff."}]} date="Stand: 06.09.2026 (BEISPIEL)"/>}
  {view==="sensitive" && <EHSensitiveServicePage kind="notfall" title="Notfall (BEISPIEL)" text="Beispielansicht. Es wird keine Hilfe beauftragt." scopeNotice={{title:"Leistungsgrenze (BEISPIEL)",text:"Diese Ansicht ersetzt keinen Notruf. Im Ernstfall wähle den Notruf."}} nextStep={{label:"Weiter (BEISPIEL, ohne Funktion)",href:"#sensitive"}} steps={[{title:"Beschreiben",text:"Was ist passiert? (BEISPIEL)"},{title:"Einordnen",text:"Dringlichkeit klären. (BEISPIEL)"}]} faq={[{q:"Wird etwas beauftragt?",a:"Nein. Beauftragung nur nach ausdrücklicher Entscheidung."}]} more={[{title:"Versicherung (BEISPIEL)",href:"#sensitive",text:"Verwandte Leistung."}]}/>}
</main><EHDialog open={dialog} onClose={()=>setDialog(false)} title="Komponente im Einsatz" actions={<EHButton onClick={()=>setDialog(false)}>Verstanden</EHButton>}><EHText>{receipt || "Ein nativer Dialog mit Tastaturfokus und Escape-Unterstützung."}</EHText></EHDialog></EHScope>;
}
