import Link from 'next/link';
import { CalendarDays,ChevronRight,ClipboardList,MapPin,ShieldAlert } from 'lucide-react';
import { AppShell,SectionTitle } from '@/components/shell';
import { requireUser } from '@/lib/auth';
import { db } from '@/lib/db';
import { dateLabel,euro } from '@/lib/format';
import { distanceKm } from '@/lib/geocode';
function areaMatch(p:any,j:any){if(Number.isFinite(p.lat)&&Number.isFinite(p.lon)&&Number.isFinite(j.lat)&&Number.isFinite(j.lon))return distanceKm({lat:p.lat,lon:p.lon},{lat:j.lat,lon:j.lon})<=p.radius_km;if(!p.postcode||!j.postcode)return true;if(p.postcode===j.postcode)return true;const a=Number(p.postcode.slice(0,2)),b=Number(j.postcode.slice(0,2));if(!Number.isFinite(a)||!Number.isFinite(b))return true;const tolerance=p.radius_km>=100?3:p.radius_km>=50?2:1;return Math.abs(a-b)<=tolerance;}
export default async function Pro(){const u=await requireUser('provider');const p=db.prepare('SELECT * FROM provider_profiles WHERE user_id=?').get(u.id) as any;if(!p?.verified)return <AppShell role="provider" active="/pro" title={`Guten Tag, ${u.first_name}!`} subtitle="Partnerkonto"><div className="verification-gate"><ShieldAlert/><h2>Partnerprüfung ausstehend</h2><p>Nur geprüfte Fachbetriebe erhalten Kundenanfragen und können Angebote abgeben.</p><Link className="btn light" href="/pro/profile">Prüfung abschließen</Link></div></AppShell>;const trades=(p?.trades||'').toLowerCase().split(',').map((x:string)=>x.trim()).filter(Boolean);const rows=db.prepare(`SELECT j.*,(SELECT path FROM job_photos p WHERE p.job_id=j.id LIMIT 1) photo,(SELECT amount FROM quotes q WHERE q.job_id=j.id AND q.provider_id=?) my_quote FROM jobs j WHERE j.status IN ('open','quoted') ORDER BY j.created_at DESC LIMIT 50`).all(u.id) as any[];const jobs=rows.filter(j=>(!trades.length||trades.some((t:string)=>j.category.toLowerCase().includes(t)||j.description.toLowerCase().includes(t)))&&areaMatch(p,j));const open=db.prepare(`SELECT COUNT(*) c FROM quotes q JOIN jobs j ON j.id=q.job_id WHERE q.provider_id=? AND q.status='accepted' AND j.status!='completed'`).get(u.id) as any;const today=db.prepare(`SELECT COUNT(*) c FROM appointments WHERE provider_id=? AND date(start_at)=date('now','localtime') AND status='confirmed'`).get(u.id) as any;return <AppShell role="provider" active="/pro" title={`Guten Morgen, ${u.first_name}!`} subtitle="Hier sind deine neuen Anfragen"><div className="metrics"><div><small>Neue Anfragen</small><b>{jobs.filter(j=>!j.my_quote).length}</b></div><div><small>Offene Aufträge</small><b>{open.c}</b></div><div><small>Heute</small><b>{today.c} Termine</b></div></div><SectionTitle>Neue Anfragen</SectionTitle><div className="stack">{jobs.slice(0,8).map((j,i)=><Link href={`/pro/jobs/${j.id}`} className="pro-request" key={j.id}><div className="request-main">{i===0&&!j.my_quote&&<span className="new">NEU</span>}<strong>{j.title}</strong><small><MapPin/>{j.postcode||'Region offen'}</small><small><CalendarDays/>{dateLabel(j.preferred_date)}</small><small><ClipboardList/>ca. {j.description.length>70?j.description.slice(0,70)+'…':j.description}</small><span>geschätztes Budget</span><b>{j.budget_min&&j.budget_max?`${euro(j.budget_min)} – ${euro(j.budget_max)}`:euro(j.budget_max)}</b></div>{j.photo&&<img src={j.photo} alt=""/>}<ChevronRight/>{j.my_quote&&<span className="quoted-badge">Angebot {euro(j.my_quote)}</span>}</Link>)}{jobs.length===0&&<div className="empty dark-empty"><ClipboardList/><strong>Aktuell keine passenden Anfragen</strong><p>Es werden nur Anfragen aus deinen Gewerken und deiner Region angezeigt.</p></div>}</div></AppShell>}
