import Link from 'next/link';
import { CalendarDays,ChevronRight,ClipboardList,MapPin,ShieldAlert,ShieldCheck,Users } from 'lucide-react';
import { AppShell,SectionTitle } from '@/components/shell';
import { requireUser } from '@/lib/auth';
import { db } from '@/lib/db';
import { dateLabel,euro,statusLabel } from '@/lib/format';
import { getProviderContext } from '@/lib/provider';

export default async function Pro(){
  const u=await requireUser('provider'); const ctx=getProviderContext(u.id);
  if(!ctx)return <AppShell role="provider" active="/pro" title={`Guten Tag, ${u.first_name}!`} subtitle="Partnerzugang"><div className="verification-gate"><ShieldAlert/><h2>Keinem Unternehmen zugeordnet</h2><p>Dein App-Zugang ist aktuell keinem aktiven Partnerunternehmen zugeordnet.</p></div></AppShell>;
  const p=db.prepare(`SELECT p.*,c.status contract_status,c.customer_discount_bps,c.insurance_verified,c.qualification_verified,c.contract_verified,c.quality_standard_verified,c.response_target_minutes FROM provider_profiles p LEFT JOIN partner_contracts c ON c.provider_id=p.user_id WHERE p.user_id=?`).get(ctx.providerId) as any;
  if(!p?.verified||p.contract_status!=='active')return <AppShell role="provider" active="/pro" title={`Guten Tag, ${u.first_name}!`} subtitle={ctx.businessName}><div className="verification-gate"><ShieldAlert/><h2>{!p?.verified?'Unternehmensprüfung ausstehend':'Partnervertrag noch nicht aktiv'}</h2><p>Einfach Hausen arbeitet nur mit geprüften, vertraglich gebundenen regionalen Unternehmen. Der Firmeninhaber sieht den Prüf- und Vertragsstatus im Profil.</p><Link className="btn light" href="/pro/profile">Partnerstatus ansehen</Link></div></AppShell>;

  const requests=ctx.canManageJobs?db.prepare(`SELECT d.id dispatch_id,d.status dispatch_status,d.match_score,d.distance_km,d.sent_at,j.*,(SELECT path FROM job_photos x WHERE x.job_id=j.id LIMIT 1) photo,(SELECT amount FROM quotes q WHERE q.job_id=j.id AND q.provider_id=?) my_quote FROM job_dispatches d JOIN jobs j ON j.id=d.job_id WHERE d.provider_id=? AND d.status IN ('sent','viewed','quoted') AND j.status IN ('open','quoted') ORDER BY d.sent_at DESC LIMIT 30`).all(ctx.providerId,ctx.providerId) as any[]:[];
  const assigned=db.prepare(`SELECT j.*,q.amount,u.first_name homeowner_first,u.last_name homeowner_last FROM job_assignments a JOIN jobs j ON j.id=a.job_id LEFT JOIN quotes q ON q.id=j.accepted_quote_id JOIN users u ON u.id=j.homeowner_id WHERE a.provider_id=? AND a.contact_user_id=? AND j.status IN ('accepted','in_progress') ORDER BY j.updated_at DESC LIMIT 30`).all(ctx.providerId,u.id) as any[];
  const companyOpen=(db.prepare(`SELECT COUNT(*) c FROM job_dispatches d JOIN jobs j ON j.id=d.job_id WHERE d.provider_id=? AND d.status='accepted' AND j.status!='completed'`).get(ctx.providerId) as any).c;
  const today=(db.prepare(`SELECT COUNT(*) c FROM appointments WHERE contact_user_id=? AND date(start_at)=date('now','localtime') AND status='confirmed'`).get(u.id) as any).c;
  const sub=db.prepare(`SELECT s.status,p.title FROM partner_subscriptions s JOIN partner_plans p ON p.slug=s.plan_slug WHERE s.provider_id=?`).get(ctx.providerId) as any;
  return <AppShell role="provider" active="/pro" title={`Guten Morgen, ${u.first_name}!`} subtitle={`${ctx.businessName} · ${ctx.jobTitle||'Ansprechpartner'}`}>
    <div className="partner-standard-banner"><ShieldCheck/><div><strong>Aktiver Vertragspartner · 0 % Provision</strong><small>{sub?.status==='active'||sub?.status==='trialing'?`${sub.title} · `:'Free · '}keine Gebühr pro Auftrag · Reaktionsziel {p.response_target_minutes} Min.</small></div></div>
    <div className="metrics"><div><small>{ctx.canManageJobs?'Neue Anfragen':'Meine Aufträge'}</small><b>{ctx.canManageJobs?requests.filter(j=>j.dispatch_status==='sent').length:assigned.length}</b></div><div><small>Firma offen</small><b>{companyOpen}</b></div><div><small>Heute</small><b>{today} Termine</b></div></div>

    {ctx.canManageJobs&&<><SectionTitle>Neue passende Anfragen</SectionTitle><div className="stack">{requests.map((j,i)=><Link href={`/pro/jobs/${j.id}`} className="pro-request" key={j.dispatch_id}><div className="request-main">{i===0&&!j.my_quote&&<span className="new">NEU</span>}<strong>{j.title.replace(/^Ansprechpartner:\s*/,'')}</strong><small><MapPin/>{j.postcode||'Region'}</small>{j.request_kind!=='contact'&&<small><CalendarDays/>{dateLabel(j.preferred_date)}</small>}<small><ClipboardList/>{j.description.length>82?j.description.slice(0,82)+'…':j.description}</small>{j.request_kind==='contact'?<><span>Kontaktanfrage</span><b>Kein Angebot nötig</b></>:<><span>KI-Richtpreis</span><b>{j.budget_min&&j.budget_max?`${euro(j.budget_min)} – ${euro(j.budget_max)}`:euro(j.budget_max)}</b></>}</div>{j.photo&&<img src={j.photo} alt=""/>}<ChevronRight/>{j.my_quote&&<span className="quoted-badge">Dein Angebot {euro(j.my_quote)}</span>}</Link>)}{requests.length===0&&<div className="empty dark-empty"><ClipboardList/><strong>Keine neue passende Anfrage</strong><p>Du erhältst nur Jobs, die zu Gewerken, Region und Qualitätsstandard passen. Bezahlte Tarife kaufen keine bessere Ranking-Position.</p></div>}</div></>}

    <SectionTitle>{ctx.canManageJobs?'Meine zugewiesenen Aufträge':'Meine Aufträge'}</SectionTitle><div className="stack">{assigned.map(j=><Link href={`/pro/jobs/${j.id}`} className="pro-request simple" key={j.id}><ClipboardList/><div className="grow"><strong>{j.title.replace(/^Ansprechpartner:\s*/,'')}</strong><small>{j.homeowner_first} {j.homeowner_last} · {statusLabel(j.status)}</small></div><b>{j.request_kind==='contact'?'Kontakt':euro(j.amount)}</b></Link>)}{assigned.length===0&&<div className="empty dark-empty"><Users/><strong>Noch kein Auftrag zugewiesen</strong><p>{ctx.canManageJobs?'Nach einer Kundenbuchung kannst du den Auftrag dir selbst oder einem Ansprechpartner zuweisen.':'Du siehst hier nur Aufträge, die dir konkret zugewiesen wurden.'}</p></div>}</div>
  </AppShell>;
}
