import { BadgeCheck,Database,FileWarning,Handshake,LogOut,ShieldCheck } from 'lucide-react';
import Link from 'next/link';
import { requireAdmin } from '@/lib/admin-auth';
import { db } from '@/lib/db';
import { adminLogoutAction,adminReviewVerificationAction,adminUpdateClaimAction,adminUpdatePartnerContractAction } from '@/app/actions';
import { statusLabel } from '@/lib/format';

export default async function Admin(){
  await requireAdmin();
  const verifications=db.prepare(`SELECT v.*,u.email,u.first_name,u.last_name,p.business_name,p.trades,p.postcode,p.verified,c.status contract_status,c.customer_discount_bps,c.insurance_verified,c.qualification_verified,c.contract_verified,c.quality_standard_verified,c.response_target_minutes,c.notes contract_notes
    FROM verification_requests v JOIN users u ON u.id=v.provider_id JOIN provider_profiles p ON p.user_id=v.provider_id LEFT JOIN partner_contracts c ON c.provider_id=v.provider_id
    ORDER BY CASE v.status WHEN 'pending' THEN 0 ELSE 1 END,v.submitted_at DESC`).all() as any[];
  const claims=db.prepare(`SELECT c.*,j.title,hu.email homeowner_email,pu.email provider_email,p.business_name FROM claims c JOIN jobs j ON j.id=c.job_id JOIN users hu ON hu.id=c.homeowner_id JOIN users pu ON pu.id=c.provider_id JOIN provider_profiles p ON p.user_id=c.provider_id ORDER BY CASE c.status WHEN 'pending' THEN 0 WHEN 'reviewing' THEN 1 ELSE 2 END,c.updated_at DESC`).all() as any[];
  return <main className="admin-page"><header className="admin-header"><div><h1>Einfach Hausen · Admin</h1><p>Vertragspartner, Qualitätsstandards, Leads und Servicefälle.</p></div><div className="action-row"><Link href="/admin/crm" className="btn primary"><Database size={16}/>Leads & CRM</Link><form action={adminLogoutAction}><button className="btn ghost"><LogOut size={16}/>Abmelden</button></form></div></header><div className="admin-grid">
    <section className="admin-panel"><h2><BadgeCheck/> Partnernetzwerk</h2>{verifications.length===0&&<p className="muted">Keine Partnerprüfungen vorhanden.</p>}<div className="stack">{verifications.map(v=><article className="admin-card" key={v.id}><div className="admin-card-head"><div><strong>{v.business_name}</strong><small>{v.first_name} {v.last_name} · {v.email}<br/>{v.trades} · {v.postcode}</small></div><div className="admin-status-stack"><span className={`status ${v.status}`}>Prüfung {statusLabel(v.status)}</span><span className={`status ${v.contract_status}`}>Vertrag {statusLabel(v.contract_status||'pending')}</span></div></div><a className="admin-file" href={`/api/admin/verification-file/${v.id}`} target="_blank" rel="noreferrer">Prüfdokument öffnen</a>{v.provider_note&&<p>{v.provider_note}</p>}
      <form action={adminReviewVerificationAction.bind(null,v.id)} className="admin-form"><textarea name="adminNote" rows={2} defaultValue={v.admin_note||''} placeholder="Prüfnotiz"/><div className="action-row"><button name="decision" value="approved" className="btn primary"><ShieldCheck size={16}/>Unternehmen freigeben</button><button name="decision" value="rejected" className="btn ghost">Ablehnen</button></div></form>
      <div className="admin-contract"><h3><Handshake size={16}/> Einfach-Hausen-Partnervertrag</h3><form action={adminUpdatePartnerContractAction.bind(null,v.provider_id)} className="admin-form"><div className="two"><label>Status<select name="status" defaultValue={v.contract_status||'pending'}><option value="pending">Ausstehend</option><option value="active">Aktiv</option><option value="suspended">Pausiert</option><option value="ended">Beendet</option></select></label><label>Reaktionsziel (Min.)<input name="responseTarget" type="number" min="5" max="240" defaultValue={v.response_target_minutes||30}/></label></div><div className="admin-zero-commission"><strong>0 % Auftragsprovision</strong><span>Partner behalten 100 % ihres Auftragswertes. Monetarisierung erfolgt ausschließlich über Partner-Tarife.</span></div><label>Kundenvorteil (bps)<input name="discountBps" type="number" min="0" max="3000" defaultValue={v.customer_discount_bps??0}/></label><div className="contract-checkboxes"><label><input type="checkbox" name="insurance" defaultChecked={!!v.insurance_verified}/> Betriebshaftpflicht geprüft</label><label><input type="checkbox" name="qualification" defaultChecked={!!v.qualification_verified}/> Qualifikation/Zulassung geprüft</label><label><input type="checkbox" name="contract" defaultChecked={!!v.contract_verified}/> Partnervertrag unterschrieben</label><label><input type="checkbox" name="quality" defaultChecked={!!v.quality_standard_verified}/> Qualitätsstandard akzeptiert</label></div><textarea name="contractNotes" rows={2} defaultValue={v.contract_notes||''} placeholder="Konditionen / interne Notizen"/><button className="btn dark">Partnervertrag speichern</button></form></div>
    </article>)}</div></section>
    <section className="admin-panel"><h2><FileWarning/> Servicefälle</h2>{claims.length===0&&<p className="muted">Keine Servicefälle vorhanden.</p>}<div className="stack">{claims.map(c=><article className="admin-card" key={c.id}><div className="admin-card-head"><div><strong>{c.title}</strong><small>Kunde: {c.homeowner_email}<br/>Partner: {c.business_name} · {c.provider_email}</small></div><span className={`status ${c.status}`}>{statusLabel(c.status)}</span></div><p>{c.description}</p><form action={adminUpdateClaimAction.bind(null,c.id)} className="admin-form"><label>Status<select name="status" defaultValue={c.status}><option value="pending">Offen</option><option value="reviewing">In Prüfung</option><option value="resolved">Gelöst</option><option value="rejected">Abgelehnt</option></select></label><textarea name="adminNote" rows={3} defaultValue={c.admin_note||''} placeholder="Rückmeldung / Entscheidung"/><button className="btn primary">Fall aktualisieren</button></form></article>)}</div></section>
  </div></main>;
}
