import { chromium } from 'playwright-core';

const base='http://127.0.0.1:3001';
const browser=await chromium.launch({headless:true,executablePath:'/Applications/Google Chrome.app/Contents/MacOS/Google Chrome'});
const owner=await browser.newContext({viewport:{width:390,height:844}});
const op=await owner.newPage();
const stamp=Date.now();
const ownerEmail=`owner-${stamp}@example.test`;
const providerEmail=`pro-${stamp}@example.test`;
const adminPassword=process.env.E2E_ADMIN_PASSWORD;
if(!adminPassword) throw new Error('E2E_ADMIN_PASSWORD is required');

await op.goto(base+'/register?role=homeowner');
await op.getByLabel('Vorname').fill('Maria');
await op.getByLabel('Nachname').fill('Test');
await op.getByLabel('E-Mail').fill(ownerEmail);
await op.getByLabel('Passwort').fill('Hausmeister!2026');
await op.getByLabel('PLZ').fill('46325');
await Promise.all([op.waitForURL('**/app'),op.getByRole('button',{name:'Konto erstellen'}).click()]);
await op.getByPlaceholder(/Meine Hecke/).fill('Meine Hecke muss geschnitten werden. Ich habe Dienstag um 14 Uhr Zeit. 46325 Borken. Budget bis 170 €.');
await Promise.all([op.waitForURL(/\/app\/jobs\/\d+/),op.getByRole('button',{name:/KI-Hausmeister/}).click()]);
const jobUrl=op.url();
const jobId=Number(jobUrl.match(/jobs\/(\d+)/)?.[1]);
if(!jobId) throw new Error('job id missing');
await op.screenshot({path:'artifacts/owner-job.png',fullPage:true});

const provider=await browser.newContext({viewport:{width:390,height:844}});
const pp=await provider.newPage();
await pp.goto(base+'/register?role=provider');
await pp.getByLabel('Vorname').fill('Thomas');
await pp.getByLabel('Nachname').fill('Müller');
await pp.getByLabel('E-Mail').fill(providerEmail);
await pp.getByLabel('Passwort').fill('Hausmeister!2026');
await pp.getByLabel('Firmenname').fill('Gartenbau Müller');
await pp.getByLabel('Gewerke').fill('Garten');
await pp.getByLabel('PLZ').fill('46325');
await Promise.all([pp.waitForURL('**/pro'),pp.getByRole('button',{name:'Konto erstellen'}).click()]);
await pp.goto(base+'/pro/profile');
await pp.getByLabel('Nachweis').setInputFiles({name:'gewerbe.pdf',mimeType:'application/pdf',buffer:Buffer.from('%PDF-1.4\n% Gewerbenachweis Test\n')});
await pp.getByLabel('Hinweis').fill('Gewerbeanmeldung und Betriebshaftpflicht liegen vor.');
await pp.getByRole('button',{name:'Zur Prüfung einreichen'}).click();
await pp.waitForURL(/verification=submitted/);
const admin=await browser.newContext({viewport:{width:1180,height:900}});
const ap=await admin.newPage();
await ap.goto(base+'/admin/login');
await ap.getByLabel('Admin-Passwort').fill(adminPassword);
await Promise.all([ap.waitForURL('**/admin'),ap.getByRole('button',{name:'Admin anmelden'}).click()]);
const verifyCard=ap.locator('.admin-card').filter({hasText:'Gartenbau Müller'}).first();
await verifyCard.getByRole('button',{name:'Freigeben'}).click();
await verifyCard.getByText('Freigegeben').waitFor();
await pp.goto(base+'/pro');
await pp.getByText('Heckenschnitt').first().click();
await pp.getByLabel('Preis (€)').fill('139');
await pp.getByRole('textbox',{name:'Nachricht',exact:true}).fill('Heckenschnitt inkl. Abtransport des Schnittguts.');
await pp.getByRole('button',{name:'Angebot senden'}).click();
await pp.waitForTimeout(500);
await pp.screenshot({path:'artifacts/provider-offer.png',fullPage:true});

await op.goto(base+`/app/jobs/${jobId}`);
await op.getByText('Gartenbau Müller').waitFor();
await op.getByRole('button',{name:'Angebot annehmen'}).click();
await op.waitForTimeout(500);
await op.locator('.detail-head .status').getByText('Beauftragt',{exact:true}).waitFor();
await op.getByPlaceholder('Nachricht schreiben …').fill('Danke, bis Dienstag!');
await op.locator('.chat-form button').click();
await op.waitForTimeout(300);
await op.screenshot({path:'artifacts/owner-accepted.png',fullPage:true});

await pp.goto(base+`/pro/jobs/${jobId}`);
await pp.getByText(/verbindlich erteilt/).waitFor();
await pp.getByRole('button',{name:'Arbeit starten'}).click();
await pp.waitForTimeout(300);
await pp.getByRole('button',{name:'Als erledigt markieren'}).click();
await pp.waitForTimeout(300);
await pp.getByLabel('Titel').fill('Leistungsnachweis Heckenschnitt');
await pp.getByLabel('Dokumenttyp').selectOption('report');
await pp.getByLabel('Datei').setInputFiles({name:'nachweis.pdf',mimeType:'application/pdf',buffer:Buffer.from('%PDF-1.4\n% Mein Hausmeister Test\n')});
await pp.getByRole('button',{name:'Dokument hochladen'}).click();
await pp.waitForTimeout(300);
await pp.screenshot({path:'artifacts/provider-completed.png',fullPage:true});

await op.goto(base+`/app/jobs/${jobId}`);
await op.getByText('Bewertung',{exact:true}).waitFor();
await op.getByPlaceholder(/Beschreibe möglichst genau/).fill('Die Ausführung soll von der Plattform geprüft werden, weil noch eine Rückfrage zur Qualität offen ist.');
await op.getByRole('button',{name:'Problem melden'}).click();
await op.waitForTimeout(300);
await op.getByText(/Problemfall · Offen/).waitFor();
await op.goto(base+'/app/documents');
await op.getByText('Leistungsnachweis Heckenschnitt').waitFor();
await pp.goto(base+`/pro/jobs/${jobId}`);
await pp.getByText(/Problemfall gemeldet · Offen/).waitFor();
await ap.goto(base+'/admin');
const claimCard=ap.locator('.admin-card').filter({hasText:'Die Ausführung soll von der Plattform geprüft werden'}).first();
await claimCard.getByLabel('Status').selectOption('resolved');
await claimCard.getByPlaceholder('Rückmeldung / Entscheidung').fill('Fall geprüft und mit beiden Seiten geklärt.');
await claimCard.getByRole('button',{name:'Fall aktualisieren'}).click();
await claimCard.locator('.status.resolved').getByText('Gelöst',{exact:true}).waitFor();
await op.goto(base+`/app/jobs/${jobId}`);
await op.getByText(/Problemfall · Gelöst/).waitFor();
await op.goto(base+'/notifications');
await op.getByText('Problemfall aktualisiert').first().waitFor();
console.log(JSON.stringify({ok:true,jobId,ownerEmail,providerEmail,jobUrl},null,2));
await browser.close();
