import Link from 'next/link';
import { Logo } from '@/components/logo';
import { registerAction } from '@/app/actions';
import { db } from '@/lib/db';

export default async function Register({searchParams}:{searchParams:Promise<Record<string,string>>}){
  const sp=await searchParams; const provider=sp.role==='provider'; const initialRequest=!provider?String(sp.request||'').trim().slice(0,700):'';
  const categories=provider?db.prepare(`SELECT slug,title,description FROM provider_categories WHERE active=1 ORDER BY CASE slug WHEN 'handwerk' THEN 1 WHEN 'dienstleistung' THEN 2 WHEN 'makler' THEN 3 WHEN 'gutachter' THEN 4 ELSE 9 END,title`).all() as any[]:[];
  const services=provider?db.prepare(`SELECT slug,title,category FROM service_catalog WHERE active=1 ORDER BY category,title`).all() as any[]:[];
  return <main className="auth-page"><form action={registerAction} className="auth-card wide-card"><Logo/><h1>{provider?'Als Anbieter starten':'Dein Zuhause organisieren'}</h1><p>{provider?'Ein Konto für dein Unternehmen. Tätigkeiten und Leistungen kannst du jederzeit erweitern.':'Ein Ansprechpartner, dein Hauswissen und Aufträge an einem Ort.'}</p>{sp.error&&<div className="alert error">{sp.error}</div>}<input type="hidden" name="role" value={provider?'provider':'homeowner'}/>{initialRequest&&<><div className="register-intent-preview"><small>Dein Anliegen</small><strong>{initialRequest}</strong><span>Nach der Anmeldung machen wir genau hier weiter.</span></div><input type="hidden" name="initialRequest" value={initialRequest}/></>}<div className="two"><label>Vorname<input name="firstName" required/></label><label>Nachname<input name="lastName" required/></label></div><label>E-Mail<input name="email" type="email" required/></label><label>Telefon<input name="phone" type="tel" placeholder="+49 …"/></label><label>Passwort<input name="password" type="password" minLength={8} required/><small>Mindestens 8 Zeichen</small></label>{provider?<>
    <label>Firmenname<input name="businessName" required/></label>
    <fieldset className="provider-category-picker"><legend>Was macht ihr?</legend><p>Mehrfachauswahl möglich. Das bestimmt nur passende Funktionen – nicht dein Login.</p><div>{categories.map((c:any)=><label key={c.slug}><input type="checkbox" name="providerCategory" value={c.slug} defaultChecked={c.slug==='handwerk'}/><span><strong>{c.title}</strong><small>{c.description}</small></span></label>)}</div></fieldset>
    <label>Leistungen / Gewerke<input name="trades" placeholder="z. B. Sanitär, Heizung, Garten" required/></label>
    <fieldset className="service-offering-picker"><legend>Konkrete Leistungen <small>(optional)</small></legend><div>{services.map((service:any)=><label key={service.slug}><input type="checkbox" name="serviceSlug" value={service.slug}/><span>{service.title}</span></label>)}</div></fieldset>
    <label>Logo <small>(optional)</small><input name="logo" type="file" accept="image/*"/></label>
    <label>Firmenanschrift<input name="streetAddress" placeholder="Straße Hausnr., Ort"/></label>
    <div className="two"><label>PLZ Einsatzgebiet<input name="postcode" inputMode="numeric" required/></label><label>Radius (km)<input name="radius" type="number" defaultValue="25" min="1" max="200"/></label></div>
    <label>Kurzbeschreibung<textarea name="description" rows={3} placeholder="Was macht euren Betrieb aus?"/></label>
    <div className="register-options"><strong>Welche Anfragen möchtest du bekommen?</strong><label><input type="checkbox" name="acceptsConsultation" defaultChecked/> Beratung / Fachfragen</label><label><input type="checkbox" name="acceptsShortNotice" defaultChecked/> Kurzfristige Aufträge</label><label><input type="checkbox" name="acceptsEmergencies"/> Notfallanfragen</label></div>
    <div className="two"><label>Öffnungszeiten<input name="openingHours" placeholder="Mo–Fr 08:00–18:00"/></label><label>Terminzeiten<input name="bookableHours" placeholder="Mo–Fr 09:00–17:00"/></label></div><input type="hidden" name="emergencyMode" value="local"/><input type="hidden" name="emergencyStart" value="18:00"/><input type="hidden" name="emergencyEnd" value="22:00"/><input type="hidden" name="emergencyMarkup" value="0"/>
  </>:<><label>PLZ<input name="postcode" inputMode="numeric" required/></label><label>Adresse <small>(optional)</small><input name="address"/></label></>}<button className="btn primary wide">Konto erstellen</button><small>Schon registriert? <Link href="/login">Einloggen</Link></small></form></main>;
}
