import Link from 'next/link';
import { CalendarDays,ChevronRight,MapPin,MessageCircle,Wrench } from 'lucide-react';
import { AppShell } from '@/components/shell';
import { requireUser } from '@/lib/auth';
import { db } from '@/lib/db';
import { euro,dateLabel,statusLabel } from '@/lib/format';

export default async function Jobs({searchParams}:{searchParams:Promise<Record<string,string>>}){
  const u=await requireUser('homeowner'); const sp=await searchParams; const tab=['planned','completed'].includes(sp.tab)?sp.tab:'active';
  const jobs=db.prepare(`SELECT j.*,COUNT(DISTINCT q.id) quotes,ap.business_name accepted_business FROM jobs j LEFT JOIN quotes q ON q.job_id=j.id LEFT JOIN quotes aq ON aq.id=j.accepted_quote_id LEFT JOIN provider_profiles ap ON ap.user_id=aq.provider_id WHERE j.homeowner_id=? GROUP BY j.id ORDER BY j.updated_at DESC`).all(u.id) as any[];
  const visible=jobs.filter(j=>tab==='completed'?['completed','cancelled'].includes(j.status):tab==='planned'?(j.request_kind==='service'&&j.status==='accepted'):!['completed','cancelled'].includes(j.status)&&!(j.request_kind==='service'&&j.status==='accepted'));
  return <AppShell role="homeowner" active="/app/jobs" title="Meine Aufträge" subtitle="Alles, was geplant oder in Arbeit ist">
    <div className="jobs-head"><h1>Meine Aufträge</h1><p>Termine, Angebote und erledigte Arbeiten auf einen Blick.</p></div>
    <div className="segmented-tabs job-tabs" role="navigation" aria-label="Auftragsansicht"><Link aria-current={tab==='active'?'page':undefined} className={tab==='active'?'active':''} href="/app/jobs?tab=active">Aktiv</Link><Link aria-current={tab==='planned'?'page':undefined} className={tab==='planned'?'active':''} href="/app/jobs?tab=planned">Geplant</Link><Link aria-current={tab==='completed'?'page':undefined} className={tab==='completed'?'active':''} href="/app/jobs?tab=completed">Abgeschlossen</Link></div>
    <div className="mobile-job-list">{visible.map(j=><Link href={`/app/jobs/${j.id}`} className="mobile-job-card" key={j.id}><div className="mobile-job-top"><span className={`job-type-icon ${j.request_kind==='contact'?'contact':''}`}>{j.request_kind==='contact'?<MessageCircle/>:<Wrench/>}</span><span className={`status ${j.status}`}>{j.request_kind==='contact'?'Ansprechpartner':statusLabel(j.status)}</span></div><strong>{j.title.replace(/^Ansprechpartner:\s*/,'')}</strong><div className="mobile-job-meta">{j.preferred_date&&<span><CalendarDays/>{dateLabel(j.preferred_date)}</span>}<span><MapPin/>{j.postcode}</span></div><div className="mobile-job-foot"><div><small>{j.accepted_business|| (j.request_kind==='contact'?'Persönlicher Kontakt':j.quotes?`${j.quotes} Angebote`:'Partner werden angefragt')}</small>{j.request_kind==='service'&&j.budget_max&&<b>{euro(j.budget_max)}</b>}</div><ChevronRight/></div></Link>)}{visible.length===0&&<div className="empty owner-empty-action"><Wrench aria-hidden="true"/><strong>{tab==='completed'?'Noch nichts abgeschlossen':tab==='planned'?'Noch nichts geplant':'Keine aktiven Themen'}</strong><p>{tab==='active'?'Beschreib dein nächstes Anliegen einfach dem Hausmeister. Du entscheidest danach, ob du nur eine Frage klärst, einen Ansprechpartner suchst oder einen Auftrag organisierst.':tab==='planned'?'Bestätigte Aufträge mit Termin erscheinen hier. Bis dahin kannst du deine aktiven Themen prüfen.':'Erledigte oder stornierte Aufträge erscheinen hier. Ein neues Anliegen startest du jederzeit beim Hausmeister.'}</p>{tab==='active'?<Link className="btn primary" href="/app/hausmeister"><MessageCircle size={16} aria-hidden="true"/> Anliegen beschreiben</Link>:tab==='planned'?<Link className="btn primary" href="/app/jobs?tab=active">Aktive Themen ansehen</Link>:<Link className="btn primary" href="/app/hausmeister"><MessageCircle size={16} aria-hidden="true"/> Neues Anliegen starten</Link>}</div>}</div>
  </AppShell>;
}
