import Link from 'next/link';
import { notFound } from 'next/navigation';
import { Home,ShieldCheck } from 'lucide-react';
import { getCurrentUser } from '@/lib/auth';
import { db } from '@/lib/db';
import { acceptHouseTransferAction } from '@/app/actions';
import { Logo } from '@/components/logo';

export default async function Transfer({params,searchParams}:{params:Promise<{token:string}>,searchParams:Promise<Record<string,string>>}){const {token}=await params;const sp=await searchParams;const transfer=db.prepare(`SELECT t.*,u.first_name,u.last_name,p.address FROM house_transfers t JOIN users u ON u.id=t.homeowner_id LEFT JOIN properties p ON p.id=t.property_id WHERE t.token=?`).get(token) as any;if(!transfer)notFound();const user=await getCurrentUser();return <main className="auth-page"><div className="auth-card wide-card"><Logo/><Home size={34}/><h1>Hausakte übernehmen</h1><p>{transfer.first_name} {transfer.last_name} hat die digitale Hausakte für <strong>{transfer.address||'das Zuhause'}</strong> zur Übergabe vorbereitet.</p><div className="transfer-info"><ShieldCheck/><p>Übertragen werden Hausprofil, Technik, Historie, offene Wartungen und gespeicherte Ansprechpartner. Alte private Nachrichten, Auftragszahlungen und persönliche Kommunikation bleiben beim bisherigen Eigentümer.</p></div>{sp.error&&<div className="alert error">{sp.error}</div>}{transfer.status!=='active'?<div className="alert success">Diese Hausakte wurde bereits übernommen oder die Freigabe ist nicht mehr aktiv.</div>:!user?<><Link className="btn primary wide" href="/login">Einloggen</Link><Link className="btn ghost wide" href="/register">Neues Eigentümerkonto erstellen</Link><small>Danach diesen Übergabelink erneut öffnen.</small></>:user.role!=='homeowner'?<div className="alert error">Für die Übernahme brauchst du ein Eigentümerkonto.</div>:<form action={acceptHouseTransferAction.bind(null,token)}><button className="btn primary wide">Hausakte jetzt übernehmen</button></form>}</div></main>}
